<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title> sehr viele money </title>
    <style>
        body {
            background-color: powderblue;
        }
        </style>
</head>
<body>
<img src="Screenshot_20260709_131815_Instagram(1)(1).jpg" alt="Mein Profilbild" width="200">
<h1> das is das fetteste casino der weld  </h1>
<h3> du hast zu viel geld geh gambeln du hure </h3>
<ul>
    <li> euro spin </li>
    <li> blackjack </li>
    <li> schlag den timi </li>
</ul>

</body>
</html>
